name = "TeaSeis"
uuid = "db5f7d96-a200-5343-9fc6-a259b42289b2"
version = "0.4.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"

[compat]
julia = "1"
Dates = "1"
LightXML = "0.9"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
benchmark = ["BenchmarkTools", "PkgBenchmark"]
test = ["Random", "Test"]
